name: test-proxy-suite
on:
  workflow_dispatch:

jobs:
  test:
    name: Test installation and ldd
    runs-on: ubuntu-latest
    container:
      image: node:14.17.0

    steps:
    - uses: actions/checkout@v2

    - name: Install testsuite deps
      run: |
        cd tests && npm install

    - name: Run testsuite
      run: |
        cd tests && npm run test

    services:
      pi:
        image: ghcr.io/${{ github.repository_owner }}/dockerpi:latest
        credentials:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}